/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#include "AP-REQ.h"

static asn_TYPE_member_t asn_MBR_AP_REQ_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AP_REQ, pvno),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pvno"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AP_REQ, msg_type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msg-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AP_REQ, ap_options),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_APOptions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ap-options"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AP_REQ, ticket),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Ticket,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ticket"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AP_REQ, authenticator),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EncryptedData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"authenticator"
		},
};
static const ber_tlv_tag_t asn_DEF_AP_REQ_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (14 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AP_REQ_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pvno */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* msg-type */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ap-options */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ticket */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* authenticator */
};
static asn_SEQUENCE_specifics_t asn_SPC_AP_REQ_specs_1 = {
	sizeof(struct AP_REQ),
	offsetof(struct AP_REQ, _asn_ctx),
	asn_MAP_AP_REQ_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AP_REQ = {
	"AP-REQ",
	"AP-REQ",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AP_REQ_tags_1,
	sizeof(asn_DEF_AP_REQ_tags_1)
		/sizeof(asn_DEF_AP_REQ_tags_1[0]), /* 2 */
	asn_DEF_AP_REQ_tags_1,	/* Same as above */
	sizeof(asn_DEF_AP_REQ_tags_1)
		/sizeof(asn_DEF_AP_REQ_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_AP_REQ_1,
	5,	/* Elements count */
	&asn_SPC_AP_REQ_specs_1	/* Additional specs */
};

