/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_AP_REQ_H_
#define	_AP_REQ_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "APOptions.h"
#include "Ticket.h"
#include "EncryptedData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AP-REQ */
typedef struct AP_REQ {
	long	 pvno;
	long	 msg_type;
	APOptions_t	 ap_options;
	Ticket_t	 ticket;
	EncryptedData_t	 authenticator;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AP_REQ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AP_REQ;

#ifdef __cplusplus
}
#endif

#endif	/* _AP_REQ_H_ */
#include <asn_internal.h>
