/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_APOptions_H_
#define	_APOptions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum APOptions {
	APOptions_reserved	= 0,
	APOptions_use_session_key	= 1,
	APOptions_mutual_required	= 2
} e_APOptions;

/* APOptions */
typedef BIT_STRING_t	 APOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_APOptions;
asn_struct_free_f APOptions_free;
asn_struct_print_f APOptions_print;
asn_constr_check_f APOptions_constraint;
ber_type_decoder_f APOptions_decode_ber;
der_type_encoder_f APOptions_encode_der;
xer_type_decoder_f APOptions_decode_xer;
xer_type_encoder_f APOptions_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _APOptions_H_ */
#include <asn_internal.h>
