/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#include "AS-REQ.h"

int
AS_REQ_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_KDC_REQ.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using KDC_REQ,
 * so here we adjust the DEF accordingly.
 */
static void
AS_REQ_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_KDC_REQ.free_struct;
	td->print_struct   = asn_DEF_KDC_REQ.print_struct;
	td->check_constraints = asn_DEF_KDC_REQ.check_constraints;
	td->ber_decoder    = asn_DEF_KDC_REQ.ber_decoder;
	td->der_encoder    = asn_DEF_KDC_REQ.der_encoder;
	td->xer_decoder    = asn_DEF_KDC_REQ.xer_decoder;
	td->xer_encoder    = asn_DEF_KDC_REQ.xer_encoder;
	td->uper_decoder   = asn_DEF_KDC_REQ.uper_decoder;
	td->uper_encoder   = asn_DEF_KDC_REQ.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_KDC_REQ.per_constraints;
	td->elements       = asn_DEF_KDC_REQ.elements;
	td->elements_count = asn_DEF_KDC_REQ.elements_count;
	td->specifics      = asn_DEF_KDC_REQ.specifics;
}

void
AS_REQ_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	AS_REQ_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
AS_REQ_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	AS_REQ_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
AS_REQ_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	AS_REQ_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
AS_REQ_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	AS_REQ_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
AS_REQ_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	AS_REQ_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
AS_REQ_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	AS_REQ_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const ber_tlv_tag_t asn_DEF_AS_REQ_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_AS_REQ = {
	"AS-REQ",
	"AS-REQ",
	AS_REQ_free,
	AS_REQ_print,
	AS_REQ_constraint,
	AS_REQ_decode_ber,
	AS_REQ_encode_der,
	AS_REQ_decode_xer,
	AS_REQ_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AS_REQ_tags_1,
	sizeof(asn_DEF_AS_REQ_tags_1)
		/sizeof(asn_DEF_AS_REQ_tags_1[0]), /* 2 */
	asn_DEF_AS_REQ_tags_1,	/* Same as above */
	sizeof(asn_DEF_AS_REQ_tags_1)
		/sizeof(asn_DEF_AS_REQ_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	0	/* No specifics */
};

