/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_HostAddress_H_
#define	_HostAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HostAddress */
typedef struct HostAddress {
	long	 addr_type;
	OCTET_STRING_t	 address;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HostAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HostAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _HostAddress_H_ */
#include <asn_internal.h>
