/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_KDC_REQ_BODY_H_
#define	_KDC_REQ_BODY_H_


#include <asn_application.h>

/* Including external dependencies */
#include "KDCOptions.h"
#include "Realm.h"
#include "KerberosTime.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PrincipalName;
struct HostAddresses;
struct EncryptedData;
struct Ticket;

/* KDC-REQ-BODY */
typedef struct KDC_REQ_BODY {
	KDCOptions_t	 kdc_options;
	struct PrincipalName	*cname	/* OPTIONAL */;
	Realm_t	 realm;
	struct PrincipalName	*sname	/* OPTIONAL */;
	KerberosTime_t	*from	/* OPTIONAL */;
	KerberosTime_t	 till;
	KerberosTime_t	*rtime	/* OPTIONAL */;
	long	 nonce;
	struct etype {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} etype;
	struct HostAddresses	*addresses	/* OPTIONAL */;
	struct EncryptedData	*enc_authorization_data	/* OPTIONAL */;
	struct additional_tickets {
		A_SEQUENCE_OF(struct Ticket) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *additional_tickets;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KDC_REQ_BODY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KDC_REQ_BODY;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PrincipalName.h"
#include "HostAddresses.h"
#include "EncryptedData.h"
#include "Ticket.h"

#endif	/* _KDC_REQ_BODY_H_ */
#include <asn_internal.h>
