/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#include "KDC-REQ-BODY.h"

static asn_TYPE_member_t asn_MBR_etype_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_etype_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_etype_specs_10 = {
	sizeof(struct etype),
	offsetof(struct etype, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_etype_10 = {
	"etype",
	"etype",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_etype_tags_10,
	sizeof(asn_DEF_etype_tags_10)
		/sizeof(asn_DEF_etype_tags_10[0]), /* 2 */
	asn_DEF_etype_tags_10,	/* Same as above */
	sizeof(asn_DEF_etype_tags_10)
		/sizeof(asn_DEF_etype_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_etype_10,
	1,	/* Single element */
	&asn_SPC_etype_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_additional_tickets_14[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_Ticket,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_additional_tickets_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_additional_tickets_specs_14 = {
	sizeof(struct additional_tickets),
	offsetof(struct additional_tickets, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_additional_tickets_14 = {
	"additional-tickets",
	"additional-tickets",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_additional_tickets_tags_14,
	sizeof(asn_DEF_additional_tickets_tags_14)
		/sizeof(asn_DEF_additional_tickets_tags_14[0]), /* 2 */
	asn_DEF_additional_tickets_tags_14,	/* Same as above */
	sizeof(asn_DEF_additional_tickets_tags_14)
		/sizeof(asn_DEF_additional_tickets_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_additional_tickets_14,
	1,	/* Single element */
	&asn_SPC_additional_tickets_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_KDC_REQ_BODY_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct KDC_REQ_BODY, kdc_options),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KDCOptions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"kdc-options"
		},
	{ ATF_POINTER, 1, offsetof(struct KDC_REQ_BODY, cname),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PrincipalName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cname"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KDC_REQ_BODY, realm),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Realm,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"realm"
		},
	{ ATF_POINTER, 2, offsetof(struct KDC_REQ_BODY, sname),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PrincipalName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sname"
		},
	{ ATF_POINTER, 1, offsetof(struct KDC_REQ_BODY, from),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KerberosTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"from"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KDC_REQ_BODY, till),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KerberosTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"till"
		},
	{ ATF_POINTER, 1, offsetof(struct KDC_REQ_BODY, rtime),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KerberosTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rtime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KDC_REQ_BODY, nonce),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonce"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KDC_REQ_BODY, etype),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_etype_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"etype"
		},
	{ ATF_POINTER, 3, offsetof(struct KDC_REQ_BODY, addresses),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_HostAddresses,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"addresses"
		},
	{ ATF_POINTER, 2, offsetof(struct KDC_REQ_BODY, enc_authorization_data),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EncryptedData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enc-authorization-data"
		},
	{ ATF_POINTER, 1, offsetof(struct KDC_REQ_BODY, additional_tickets),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		0,
		&asn_DEF_additional_tickets_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additional-tickets"
		},
};
static ber_tlv_tag_t asn_DEF_KDC_REQ_BODY_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_KDC_REQ_BODY_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* kdc-options */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cname */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* realm */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sname */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* from */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* till */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* rtime */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* nonce */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* etype */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* addresses */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* enc-authorization-data */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* additional-tickets */
};
static asn_SEQUENCE_specifics_t asn_SPC_KDC_REQ_BODY_specs_1 = {
	sizeof(struct KDC_REQ_BODY),
	offsetof(struct KDC_REQ_BODY, _asn_ctx),
	asn_MAP_KDC_REQ_BODY_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_KDC_REQ_BODY = {
	"KDC-REQ-BODY",
	"KDC-REQ-BODY",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_KDC_REQ_BODY_tags_1,
	sizeof(asn_DEF_KDC_REQ_BODY_tags_1)
		/sizeof(asn_DEF_KDC_REQ_BODY_tags_1[0]), /* 1 */
	asn_DEF_KDC_REQ_BODY_tags_1,	/* Same as above */
	sizeof(asn_DEF_KDC_REQ_BODY_tags_1)
		/sizeof(asn_DEF_KDC_REQ_BODY_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_KDC_REQ_BODY_1,
	12,	/* Elements count */
	&asn_SPC_KDC_REQ_BODY_specs_1	/* Additional specs */
};

