/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#include "KDC-PROXY-MESSAGE.h"

static asn_TYPE_member_t asn_MBR_KDC_PROXY_MESSAGE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct KDC_PROXY_MESSAGE, kerb_message),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"kerb-message"
		},
	{ ATF_POINTER, 2, offsetof(struct KDC_PROXY_MESSAGE, target_domain),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Realm,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"target-domain"
		},
	{ ATF_POINTER, 1, offsetof(struct KDC_PROXY_MESSAGE, dclocator_hint),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dclocator-hint"
		},
};
static ber_tlv_tag_t asn_DEF_KDC_PROXY_MESSAGE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_KDC_PROXY_MESSAGE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* kerb-message */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* target-domain */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dclocator-hint */
};
static asn_SEQUENCE_specifics_t asn_SPC_KDC_PROXY_MESSAGE_specs_1 = {
	sizeof(struct KDC_PROXY_MESSAGE),
	offsetof(struct KDC_PROXY_MESSAGE, _asn_ctx),
	asn_MAP_KDC_PROXY_MESSAGE_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_KDC_PROXY_MESSAGE = {
	"KDC-PROXY-MESSAGE",
	"KDC-PROXY-MESSAGE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_KDC_PROXY_MESSAGE_tags_1,
	sizeof(asn_DEF_KDC_PROXY_MESSAGE_tags_1)
		/sizeof(asn_DEF_KDC_PROXY_MESSAGE_tags_1[0]), /* 1 */
	asn_DEF_KDC_PROXY_MESSAGE_tags_1,	/* Same as above */
	sizeof(asn_DEF_KDC_PROXY_MESSAGE_tags_1)
		/sizeof(asn_DEF_KDC_PROXY_MESSAGE_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_KDC_PROXY_MESSAGE_1,
	3,	/* Elements count */
	&asn_SPC_KDC_PROXY_MESSAGE_specs_1	/* Additional specs */
};

