/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_KDCOptions_H_
#define	_KDCOptions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum KDCOptions {
	KDCOptions_reserved	= 0,
	KDCOptions_forwardable	= 1,
	KDCOptions_forwarded	= 2,
	KDCOptions_proxiable	= 3,
	KDCOptions_proxy	= 4,
	KDCOptions_allow_postdate	= 5,
	KDCOptions_postdated	= 6,
	KDCOptions_unused7	= 7,
	KDCOptions_renewable	= 8,
	KDCOptions_unused9	= 9,
	KDCOptions_renewable_ok	= 27,
	KDCOptions_enc_tkt_in_skey	= 28,
	KDCOptions_renew	= 30,
	KDCOptions_validate	= 31
} e_KDCOptions;

/* KDCOptions */
typedef BIT_STRING_t	 KDCOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KDCOptions;
asn_struct_free_f KDCOptions_free;
asn_struct_print_f KDCOptions_print;
asn_constr_check_f KDCOptions_constraint;
ber_type_decoder_f KDCOptions_decode_ber;
der_type_encoder_f KDCOptions_encode_der;
xer_type_decoder_f KDCOptions_decode_xer;
xer_type_encoder_f KDCOptions_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _KDCOptions_H_ */
#include <asn_internal.h>
