/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_KerberosTime_H_
#define	_KerberosTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralizedTime.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KerberosTime */
typedef GeneralizedTime_t	 KerberosTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KerberosTime;
asn_struct_free_f KerberosTime_free;
asn_struct_print_f KerberosTime_print;
asn_constr_check_f KerberosTime_constraint;
ber_type_decoder_f KerberosTime_decode_ber;
der_type_encoder_f KerberosTime_encode_der;
xer_type_decoder_f KerberosTime_decode_xer;
xer_type_encoder_f KerberosTime_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _KerberosTime_H_ */
#include <asn_internal.h>
