/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_KRB_PRIV_H_
#define	_KRB_PRIV_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "EncryptedData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KRB-PRIV */
typedef struct KRB_PRIV {
	long	 pvno;
	long	 msg_type;
	EncryptedData_t	 enc_part;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KRB_PRIV_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KRB_PRIV;

#ifdef __cplusplus
}
#endif

#endif	/* _KRB_PRIV_H_ */
#include <asn_internal.h>
