/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_PA_DATA_H_
#define	_PA_DATA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PA-DATA */
typedef struct PA_DATA {
	long	 padata_type;
	OCTET_STRING_t	 pa_data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PA_DATA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PA_DATA;

#ifdef __cplusplus
}
#endif

#endif	/* _PA_DATA_H_ */
#include <asn_internal.h>
