/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#include "PA-DATA.h"

static asn_TYPE_member_t asn_MBR_PA_DATA_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PA_DATA, padata_type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"padata-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PA_DATA, pa_data),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pa-data"
		},
};
static ber_tlv_tag_t asn_DEF_PA_DATA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PA_DATA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* padata-type */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* pa-data */
};
static asn_SEQUENCE_specifics_t asn_SPC_PA_DATA_specs_1 = {
	sizeof(struct PA_DATA),
	offsetof(struct PA_DATA, _asn_ctx),
	asn_MAP_PA_DATA_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PA_DATA = {
	"PA-DATA",
	"PA-DATA",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PA_DATA_tags_1,
	sizeof(asn_DEF_PA_DATA_tags_1)
		/sizeof(asn_DEF_PA_DATA_tags_1[0]), /* 1 */
	asn_DEF_PA_DATA_tags_1,	/* Same as above */
	sizeof(asn_DEF_PA_DATA_tags_1)
		/sizeof(asn_DEF_PA_DATA_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PA_DATA_1,
	2,	/* Elements count */
	&asn_SPC_PA_DATA_specs_1	/* Additional specs */
};

