/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_PrincipalName_H_
#define	_PrincipalName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <GeneralString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PrincipalName */
typedef struct PrincipalName {
	long	 name_type;
	struct name_string {
		A_SEQUENCE_OF(GeneralString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} name_string;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrincipalName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrincipalName;

#ifdef __cplusplus
}
#endif

#endif	/* _PrincipalName_H_ */
#include <asn_internal.h>
