/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "KKDCP"
 * 	found in "kkdcp.asn1"
 */

#ifndef	_Ticket_H_
#define	_Ticket_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Realm.h"
#include "PrincipalName.h"
#include "EncryptedData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ticket */
typedef struct Ticket {
	long	 tkt_vno;
	Realm_t	 realm;
	PrincipalName_t	 sname;
	EncryptedData_t	 enc_part;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ticket_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ticket;

#ifdef __cplusplus
}
#endif

#endif	/* _Ticket_H_ */
#include <asn_internal.h>
